wandb_version: 1

base_filters:
  desc: null
  value: 38
lr:
  desc: null
  value: 0.04671882982006516
sample_rate:
  desc: null
  value: 8000
_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.3
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685528935.055236
    t:
      1:
      - 1
      - 9
      - 50
      - 55
      2:
      - 1
      - 9
      - 50
      - 55
      3:
      - 16
      - 23
      - 37
      4: 3.11.3
      5: 0.15.3
      8:
      - 5
num_classes:
  desc: null
  value: 50
optim/lr:
  desc: null
  value: 0.04671882982006516
