seed: 0

data:
  path: "data/ESC-50-master"
  sample_rate: 8_000
  train_folds: [1, 2, 3]
  val_folds: [4]
  test_folds: [5]
  batch_size: 16

model:
  base_filters: 32
  num_classes: 50
  optim:
    lr: 3e-4

trainer:
  gpus: 1
  max_epochs: 10

defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog
